### Finally
Также, как и у
```
try {} catch {} finally {}
```
У Promise тоже есть свой finally

Он принимает в себя коллбэк без аргументов, потому что неизвестно:
он был вызван после resolve или reject. И он также ничего из себя не возвращает.
